name: Build And Release HamsterMod Release

on:
  push:
    branches: [ master ]
    paths:
    - 'src/**'
    - 'building/**'
    - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js v15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    - name: Install NPM dependencies
      run: npm ci
      
    - name: Build GooseMod
      run: npm run build

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "master"
        prerelease: false
        title: "HamsterMod Release"
        files: |
          dist/index.js
